spring:
  main:
    banner-mode: "off"
  application:
    name: imgur-feign-client
server:
  port: 443

# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: false

logging.level.org.springframework.web: debug
logging.level.org.keycloak : debug
logging.level.org.springframework.security: trace
logging.level.org.springframework.web-security: trace
logging.level.feign: DEBUG
logging.level.io.github.justinebateman.imgur.service: DEBUG

imgur:
  apiendpoint: https://api.imgur.com
  clientId: CHANGEME
  clientSecret: CHANGEME

